[package]
name = "rsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
num-bigint = "0.3"
num-traits = "0.2"
sha2 = "0.9"
num-integer = "0.1"
